services:
  - type: web
    name: medichain-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: VITE_API_BASE_URL
        value: https://medichain-backend.onrender.com
